name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Increment"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
      prerelease_type:
        description: "Pre-release identifier (e.g., alpha, beta, rc)"
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: bun install --frozen-lockfile
      - name: Run release
        run: |
          if [[ "${{ github.event.inputs.increment }}" == pre* ]]; then
            bun run release -- ${{ github.event.inputs.increment }} --preRelease=${{ github.event.inputs.prerelease_type || 'beta' }}
          else
            bun run release -- ${{ github.event.inputs.increment }}
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
